### ISSUE TITLE
License not displayed on crates.io

### ISSUE THREAD

**Issue by phoenixr-codes** [phoenixr-codes/termstatus#1]
use

```toml
[package]
license = "MIT"
```
instead.

see also: https://github.com/rust-lang/cargo/issues/8537
